apiVersion: siddhi.io/v1alpha1
kind: SiddhiProcess
metadata:
  name: energy-alert-app-siddhi-process
spec:
  size: 1
  env: 
    - name: RECEIVER_URL
      value: "http://0.0.0.0:8006"
    - name: BASIC_AUTH_ENABLED
      value: "false"

  query: |
    @App:name("Energy-Alert-App-Temp") 
    @App:description("Description of the plan") 

    @source(type='http', receiver.url='http://0.0.0.0:8006/devicePowerStream2', basic.auth.enabled='false', @map(type='json'))
    define stream DevicePowerStream (type string, deviceID string, power int);

    @sink(type='log', prefix='LOGGER')
    define stream MonitorDevicesPowerStream(deviceID string, power int);

    @info(name='monitored-filter')
    from DevicePowerStream[type == 'monitored']
    select deviceID, power
    insert into MonitorDevicesPowerStream; 
  siddhi: |
    refs:
        - ref:
          name: 'passthroughDevicePower'
          type: 'http'
          properties:
            receiver.url: ${RECEIVER_URL}/devicePowerStream
            basic.auth.enabled: ${BASIC_AUTH_ENABLED}
  




