apiVersion: siddhi.io/v1alpha1
kind: SiddhiProcess
metadata:
  name: app2
spec:
  size: 1
  ingress:
    tls:
      secretName: siddhi-tls
  env: 
    - name: RECEIVER_URL
      value: "http://0.0.0.0:8006/foo"
    - name: RECEIVER2_URL
      value: "http://0.0.0.0:8007/bar"
    - name: BASIC_AUTH_ENABLED
      value: "false"
  apps:
    - app2


  




